name: Build EAS for Production

on:
  release:
    types:
      - created

env:
  # Use Github packages
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  # Create changelog for release
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: somethingco/conventional-changelog-action
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Generate Changelog
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  # Push image to Google Container Registry
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
          
      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"

      - name: Pull, re-tag latest as prod and push image
        run: |
          IMAGE_NAME=ghcr.io/$REPOSITORY_NAME

          # Change all uppercase to lowercase
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
          REPOSITORY_NAME=$(echo $REPOSITORY_NAME | tr '[A-Z]' '[a-z]')
          
          # Pull the latest image
          docker pull $IMAGE_NAME:staging
          
          # Tag + Push semantic versioned image
          docker tag $IMAGE_NAME:staging $IMAGE_NAME:production
          docker push $IMAGE_NAME:production

